# Generated by Django 3.1.2 on 2020-10-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_model',
            name='images',
            field=models.ImageField(default='', upload_to='testapp\\images'),
        ),
        migrations.AddField(
            model_name='product_model',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='product_model',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
