# Generated by Django 3.0.6 on 2020-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_comment_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_model',
            options={'ordering': ('date_added',)},
        ),
        migrations.AddField(
            model_name='comment_model',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
