# Generated by Django 3.0.6 on 2020-10-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20201010_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_model',
            new_name='Post',
        ),
    ]
